export const ProductsPageLocators = {
  logo: '.app_logo',
  pageTitle: '.title',
  inventory: '.inventory_container',
  inventoryItems: '.inventory_item',
  inventoryItemName: '.inventory_item_name',
  inventoryItemDesc: '.inventory_item_desc',
  inventoryItemPrice: '.inventory_item_price',
  addToCartButton: '[id^="add-to-cart"]',
  removeButton: '[id^="remove"]',
  cartLink: '.shopping_cart_link',
  cartBadge: '.shopping_cart_badge',
  sortDropdown: '.product_sort_container',
  menuButton: '#react-burger-menu-btn',
  logoutLink: '#logout_sidebar_link',
  allItems: '#inventory_sidebar_link',
  About: '#about_sidebar_link',
  ResetAppState: '#reset_sidebar_link',
};
